# Generated by Django 3.1.3 on 2020-11-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_rcmd', '0006_auto_20201114_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='total_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
