# Generated by Django 3.1.3 on 2020-12-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_rcmd', '0007_movie_total_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='RcmdStat',
            fields=[
                ('timestamp', models.IntegerField(primary_key=True, serialize=False)),
                ('rcmd_click_num', models.IntegerField()),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
