# Generated by Django 3.1.3 on 2020-11-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genres', models.TextField(blank=True, max_length=300)),
                ('imdb_id', models.IntegerField(blank=True)),
                ('tmdb_id', models.IntegerField(blank=True)),
            ],
        ),
    ]
