# Generated by Django 3.1.3 on 2020-11-13 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_rcmd', '0002_auto_20201113_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='tmdb_id',
        ),
    ]
